---

- hosts: all
  become: true
  tasks: 

  - name: update repositores 
    apt: 
      update_cache: yes
    when: ansible_distribution in ["Ubuntu","Debian"]

  - name: update repository, install apache2 and php package
    package:
      name: 
        - httpd
        - php
      state: latest
      update_cache: yes
