---

- hosts: all
  become: true
  tasks: 

  - name: update repositores 
    apt: 
      update_cache: yes
    when: ansible_distribution in ["Ubuntu","Debian"]

  - name: update repositories 
    yum:
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install apache2 package
    yum:
      name: httpd
      state: latest
    when: ansible_distribution == "CentOS"

  - name: add php support for apache
    yum:
      name: php
      state: latest
    when: ansible_distribution == "CentOS"
