---

- hosts: all
  become: true
  pre_tasks: 

  - name: install updates (CentOS)
    tags: always
    yum: 
      update_only: yes 
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install updates (Ubuntu)
    tags: always
    apt: 
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: web_servers 
  become: true
  tasks: 

  - name: Install apache2 and php package
    tags: apache,httpd,centOS
    package:
      name: 
        - httpd
        - php
      state: latest

  - name: copy default html file for size 
    tags: httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

