- name: Install apache2 and php package
  tags: apache,httpd,centOS
  package:
    name: 
      - httpd
      - php
    state: latest

- name: Start httpd apache service 
  tags: apache, httpd, centOS
  service: 
    name: httpd
    state: started 
    enabled: yes
  when: ansible_distribution == "CentOS"

- name: Change email addy for admin 
  tags: apache,httpd,centOS
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^ServerAdmin'
    line: ServerAdmin somebody@somewhere.net
  when: ansible_distribution == "CentOS"
  register: httpd

- name: Restart httpd
  tags: apache,httpd,centOS
  service: 
    name: httpd
    state: restarted
  when: httpd.changed

- name: copy default html file for size 
  tags: httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644

- name: install unzip 
  package: 
    name: unzip

- name: install terraform
  unarchive: 
    src: https://releases.hashicorp.com/terraform/1.9.8/terraform_1.9.8_linux_amd64.zip
    dest: /usr/local/bin
    remote_src: yes 
    mode: 0755
    owner: root
    group: root
